.github/workflows/build.yaml, .gitignore, .gitmodules, air-quality-app-batch/build.gradle, air-quality-app-batch/src/main/resources/application.yaml, air-quality-app-batch/src/test/java/io/howstheairtoday/airqualityappbatch/AirQualityAppBatchApplicationTests.java, air-quality-app-external-api/src/main/resources/application.yaml, air-quality-app-external-api/src/test/java/io/howstheairtoday/airqualityappexternalapi/AirQualityAppExternalApiApplicationTests.java, air-quality-domain-rds/src/main/resources/application.yaml, air-quality-domain-redis/src/test/java/io/howstheairtoday/airqualitydomainredis/AirQualityDomainRedisApplicationTests.java, air-quality-domain-service/src/test/java/io/howstheairtoday/airqualitydomainservice/AirQualityDomainServiceApplicationTests.java, build.gradle, community-app-external-api/src/main/resources/application.yaml, community-app-external-api/src/test/java/io/howstheairtoday/appcommunityexternalapi/AppCommunityExternalApiApplicationTests.java, community-domain-rds/src/main/resources/application.yaml, community-domain-redis/src/test/java/io/howstheairtoday/communitydomainredis/CommunityDomainRedisApplicationTests.java, community-domain-service/src/test/java/io/howstheairtoday/communitydomainservice/CommunityDomainServiceApplicationTests.java, member-app-external-api/src/main/resources/application.yaml, member-app-external-api/src/test/java/io/howstheairtoday/appmemberexternalapi/AppMemberExternalApiApplicationTests.java, member-domain-rds/src/main/resources/application.yaml, member-domain-redis/src/test/java/io/howstheairtoday/memberdomainredis/MemberDomainRedisApplicationTests.java, member-domain-service/src/test/java/io/howstheairtoday/memberdomainservice/MemberDomainServiceApplicationTests.java
- 그레이들 빌드 시 테스트 코드가 환경 변수를 찾지 못하는 에러 발생
```bash
> Task :air-quality-app-batch:test
AirQualityAppBatchApplicationTests > contextLoads() FAILED
java.lang.IllegalStateException at DefaultCacheAwareContextLoaderDelegate.java:142
Caused by: org.springframework.boot.context.config.ConfigDataResourceNotFoundException at ConfigDataResourceNotFoundException.java:97
1 test completed, 1 failed
```
- github actions workflow 문제라고 판단하여 workflow 수정
- gradle build workflow 버전 변경
- gradle 명령어 수정
- application 모듈 테스트 코드에서 mariadb 접근을 위한 테스트 프로필 환경 변수를 불러오는 에러 발생
- 테스트 코드에서 `@ActiveProfiles("test")` 어노테이션 제거
- application 계층에서는 데이터베이스 접속 관련 환경변수를 import하지 않는데, 테스트 프로필을 활성화했기 때문에 에러 발생
- `module-common` 내에 추가한 git submodule(환경변수 레포지토리)을 각 모듈 내 `src/main/resources/security-env`로 복사하는 gradle task로 인한 문제로 판단
- …
=> 🚑 fix(HAT-133): Gradle 빌드 실패 에러 해결

air-quality-app-batch/Dockerfile, air-quality-app-external-api/Dockerfile, community-app-external-api/Dockerfile, member-app-external-api/Dockerfile
=> 👷 ci(HAT-154): 도커파일 추가

member-app-external-api/build.gradle, member-app-external-api/settings.gradle, member-app-external-api/src/main/java/io/howstheairtoday/MemberAppExternalApiApplication.java, member-app-external-api/src/main/java/io/howstheairtoday/memberappexternalapi/config/CustomSecurityConfig.java, member-app-external-api/src/main/java/io/howstheairtoday/memberappexternalapi/config/RootConfig.java, member-app-external-api/src/main/java/io/howstheairtoday/memberappexternalapi/service/MemberDetailsService.java, member-app-external-api/src/main/java/io/howstheairtoday/memberappexternalapi/service/dto/MemberLoginRequestDTO.java, member-app-external-api/src/main/java/io/howstheairtoday/memberappexternalapi/service/handler/MemberLoginSuccessHandler.java, member-app-external-api/src/main/java/io/howstheairtoday/memberappexternalapi/util/JWTUtil.java, member-app-external-api/src/test/java/io/howstheairtoday/memberappexternalapi/MemberAppExternalApiApplicationTests.java, member-app-external-api/src/test/java/io/howstheairtoday/memberappexternalapi/util/JWTUtilTest.java, module-core/build.gradle
- Token 사용을 위한 JWT 설정
- JWT 의존성을 추가
- JWT Token 설정을 위한 Util class 생성하여 Json 형식으로 받은 loginId와 loginPassword로 Token 형식으로 발급이 되는지를 확인
- JWT Token Util Test 수행: header.payload.signature 형식으로 테스트가 되는지 확인
- JWT 토큰 생성 설정 확인: 테스트 성공
- JWT 토큰 생성 유효성 검사 - 성공: 테스트 성공
- JWT 토큰 생성 유효성 검사 - 실패: 테스트 성공
- Access Token 과 Refresh Token 또한 발급확인을 하려 했지만, 회원의 아이디와 패스워드가 DB에 저장되어 있어야 확인이 가능할 것으로 판단되어 해당 부분은 기본적인 회원 가입 서비스를 먼저 구현한 후 이어서 개발할 예정임.
=> ✨ feat(HAT-144): JWT Setting

air-quality-app-batch/build.gradle, air-quality-app-external-api/build.gradle, community-app-external-api/build.gradle, member-app-external-api/build.gradle
=> 📌 build: manifest attribute 정의

air-quality-app-batch/src/main/java/io/howstheairtoday/service/AirQualityRealTimeService.java, air-quality-app-batch/src/test/java/io/howstheairtoday/airqualityappbatch/AirQualityAppBatchApplicationTests.java, air-quality-app-batch/src/test/java/io/howstheairtoday/airqualityappbatch/service/ServiceTests.java, air-quality-domain-rds/src/main/java/io/howstheairtoday/airqualitydomainrds/entity/AirQualityRealTime.java, air-quality-domain-rds/src/test/java/io/howstheairtoday/airqualitydomainrds/RepositoryTests.java
- 대기질 실시간 측정정보를 호출한 값을 데이터베이스에 삽입
- 서비스 및 테스트 추가
- 서비스에서는 642개의 데이터를 삽입하는 과정을 거침
- 테스트에서는 데이터의 개수를 세어 비교하는 결과를 도출
=> ✨ feat(HAT-77): 대기질 실시간 측정정보 삽입

air-quality-app-batch/src/test/java/io/howstheairtoday/airqualityappbatch/service/ServiceTests.java
- 프로젝트 빌드시 api 호출 오류 발생
- Mock Server를 만들어주어 미리 정해준 JSON 값을 리턴할 수 있도록 변경했습니다.
- OpenAPI 서버가 아닌, Mock Server을 호출해 값을 얻어 응답 유/무를 파악할 수 있게 변경했습니다.
=> ✅ test(HAT-179): 미세먼지 실시간 측정정보 호출 Test 수정

member-app-external-api/src/main/java/io/howstheairtoday/memberappexternalapi/security/config/CustomSecurityConfig.java
- CORS의 다른 출처 리소스 공유 정책(Cross Origin Resource Sharing) 기본 설정
- 완성단계가 아닌 개발 단계에서 테스트 각각 진행 해야하기 때문에 모든 요청에 대해서 설정하였음
- 모든 요청에 대해서 설정
=> ✨ feat(HAT-186): CORS 설정

community-app-external-api/src/main/java/io/howstheairtoday/appcommunityexternalapi/controller/CommentController.java, community-app-external-api/src/main/java/io/howstheairtoday/appcommunityexternalapi/service/CommentService.java, community-app-external-api/src/main/java/io/howstheairtoday/appcommunityexternalapi/service/dto/request/CommentRequestDTO.java, community-app-external-api/src/test/java/io/howstheairtoday/appcommunityexternalapi/controller/CommentControllerTest.java, community-app-external-api/src/test/java/io/howstheairtoday/appcommunityexternalapi/service/CommentServiceTest.java, community-domain-rds/build.gradle, community-domain-rds/src/main/java/io/howstheairtoday/communitydomainrds/entity/Comment.java, community-domain-rds/src/main/java/io/howstheairtoday/communitydomainrds/repository/CommentRepository.java, community-domain-rds/src/main/java/io/howstheairtoday/communitydomainrds/service/DomainCommunityService.java, community-domain-rds/src/test/java/io/howstheairtoday/communitydomainrds/repository/CommentRepositoryTest.java
- 게시물 댓글 수정 기능
- 댓글 수정 service 로직 구현
- service 테스트 완료
- 댓글 수정 controller 구현
- controller 테스트 완료
- Postman 테스트
- 데이터베이스
=> ✨ feat(HAT-55): 게시물 댓글 수정기능

air-quality-app-external-api/src/test/java/io/howstheairtoday/airqualityappexternalapi/service/AirQualityRealTimeServiceTest.java
- Build 시에 API 서버 상태 불안정
- API 호출을 Mock을 통한 호출로 변경
- Mock Server을 통해 미리 기대 값을 넣어둔 뒤 올바르게 호출하는지 테스트하는 것으로 변경했습니다.
=> ♻️ refactor(HAT-179): 대기질 실시간 측정정보 호출 API Test 변경

community-app-external-api/src/main/java/io/howstheairtoday/appcommunityexternalapi/controller/PostController.java, community-app-external-api/src/main/java/io/howstheairtoday/appcommunityexternalapi/exception/CommonBusinessException.java, community-app-external-api/src/main/java/io/howstheairtoday/appcommunityexternalapi/exception/GlobalExceptionHandler.java, community-app-external-api/src/main/java/io/howstheairtoday/appcommunityexternalapi/exception/dto/ErrorDto.java, community-app-external-api/src/main/java/io/howstheairtoday/appcommunityexternalapi/exception/dto/ErrorMessage.java, community-app-external-api/src/main/java/io/howstheairtoday/appcommunityexternalapi/exception/posts/PostNotExistException.java, community-app-external-api/src/main/java/io/howstheairtoday/appcommunityexternalapi/service/ExternalPostService.java, community-app-external-api/src/test/java/io/howstheairtoday/appcommunityexternalapi/service/ExternalPostServiceTest.java, community-domain-rds/src/main/java/io/howstheairtoday/communitydomainrds/entity/Post.java, community-domain-rds/src/main/java/io/howstheairtoday/communitydomainrds/entity/PostImage.java, community-domain-rds/src/main/java/io/howstheairtoday/communitydomainrds/repository/PostRepository.java, community-domain-rds/src/main/java/io/howstheairtoday/communitydomainrds/service/DomainCommunityService.java, community-domain-rds/src/test/java/io/howstheairtoday/communitydomainrds/repository/PostRepositoryTest.java
- 게시글 업데이트 
- 게시글 업데이트를 하기위해선 디비에 존재하는 게시물의 아이디를 가져와서 사용한다. 
- id가 없을경우 
-  성공했을때
=> ✨ feat(HAT-71): 게시글수정기능

member-app-external-api/src/test/java/io/howstheairtoday/memberappexternalapi/security/util/JwTUtilTest.java, module-security/src/main/java/io/howstheairtoday/config/CustomSecurityConfig.java, module-security/src/main/java/io/howstheairtoday/filter/RefreshTokenFilter.java, module-security/src/main/java/io/howstheairtoday/service/handler/LoginSuccessHandler.java, module-security/src/main/java/io/howstheairtoday/util/JwtUtil.java
- JWT payloads 내용 수정
- MemberId 값 추가
- AccessToken의 Payloads에 회원의 MemberId 값을 추가
=> ♻️  refactor(HAT-228): Add a MemberId value to the Access Token

community-app-external-api/src/main/java/io/howstheairtoday/appcommunityexternalapi/controller/PostController.java, community-app-external-api/src/main/java/io/howstheairtoday/appcommunityexternalapi/service/ExternalPostService.java, community-app-external-api/src/main/java/io/howstheairtoday/appcommunityexternalapi/service/dto/request/PostRequestDto.java, community-app-external-api/src/test/java/io/howstheairtoday/appcommunityexternalapi/service/ExternalPostServiceTest.java, community-domain-rds/src/test/java/io/howstheairtoday/communitydomainrds/repository/PostRepositoryTest.java
- 게시글 삭제기능 
- Id 를 못찾았을경우 `Excecption` handler 가 잡아줘서 에러 . 
-
=> ✨ feat(HAT-72): 게시글삭제기능

build.gradle, community-app-external-api/src/main/java/io/howstheairtoday/appcommunityexternalapi/controller/PostController.java, community-app-external-api/src/main/java/io/howstheairtoday/appcommunityexternalapi/service/ExternalPostService.java, community-app-external-api/src/main/java/io/howstheairtoday/appcommunityexternalapi/service/dto/response/PostResponseDto.java, community-app-external-api/src/test/java/io/howstheairtoday/appcommunityexternalapi/service/ExternalPostServiceTest.java, community-domain-rds/src/main/java/io/howstheairtoday/communitydomainrds/entity/Post.java, community-domain-rds/src/main/java/io/howstheairtoday/communitydomainrds/entity/PostImage.java, community-domain-rds/src/test/java/io/howstheairtoday/communitydomainrds/repository/PostRepositoryTest.java
- 게시글상세 기능 
- `memberId`를 params로 추가해 자신이 쓴게시글을 조회한다 .
=> ✨feat(HAT-230): 지역별 커뮤니티 게시물상세 

community-app-external-api/src/main/java/io/howstheairtoday/appcommunityexternalapi/controller/PostController.java
- ingress.yaml 작성을 위한 api 통일
- requestMapping에 post를 추가해주고 모든 메서드 Mapping에 post 제거
- URL 주소를 변경해주었습니다.
=> ♻️ refector: Post API 통일

community-app-external-api/src/main/java/io/howstheairtoday/appcommunityexternalapi/config/MultiPartJacksonConfig.java, community-app-external-api/src/main/java/io/howstheairtoday/appcommunityexternalapi/controller/PostController.java, community-app-external-api/src/main/java/io/howstheairtoday/appcommunityexternalapi/service/ExternalPostService.java, community-app-external-api/src/main/java/io/howstheairtoday/appcommunityexternalapi/service/dto/request/PostRequestDto.java, community-app-external-api/src/main/java/io/howstheairtoday/appcommunityexternalapi/service/dto/response/PostResponseDto.java, community-app-external-api/src/test/java/io/howstheairtoday/appcommunityexternalapi/service/ExternalPostServiceTest.java, community-domain-rds/src/main/java/io/howstheairtoday/communitydomainrds/dto/DomainPostResponseDto.java, community-domain-rds/src/main/java/io/howstheairtoday/communitydomainrds/entity/PostImage.java, community-domain-rds/src/main/java/io/howstheairtoday/communitydomainrds/repository/PostRepository.java, community-domain-rds/src/main/java/io/howstheairtoday/communitydomainrds/service/DomainCommunityService.java
- 기존에 있던 코드를 수정 
- MultiPart 컨버터를 등록한이유는 하나의 단일 이미지일경우는 데이터가 보내지지만, List형식으로 보낼땐 지원을 하지않아, 다음 리팩토링때 이미지 여러개일경우를 대비해서 등록함.
=> ♻️ refector(HAT-285) 백엔드게시물작성게시물수정

member-app-external-api/src/main/java/io/howstheairtoday/memberappexternalapi/controller/AuthController.java, member-app-external-api/src/main/java/io/howstheairtoday/memberappexternalapi/service/AuthService.java
- 회원 프로필 기능 코드 수정
- 프론트 구성, AWS S3 기능 추가로 인한 수정 사항
- 1: 회원가입시 기본 이미지를 AWS S3에 업로드한 기본 이미지를 불러오게 하였음.
- 2: AWS S3 프로필 업로드시, response 값으로 url값을 출력하도록 수정 
- 프론트 구성중 프로필 이미지에 대한 서버에서 필요한 값을 수정했습니다.
=> ♻️  refactor: 회원가입 및 S3 업로드 코드 수정

community-app-external-api/src/main/java/io/howstheairtoday/appcommunityexternalapi/service/ExternalPostService.java, community-app-external-api/src/main/java/io/howstheairtoday/appcommunityexternalapi/service/dto/request/PostRequestDto.java, community-app-external-api/src/test/java/io/howstheairtoday/appcommunityexternalapi/service/ExternalPostServiceTest.java, community-domain-rds/src/main/java/io/howstheairtoday/communitydomainrds/entity/Post.java
- 게시물작성 수정 
- 피드에서 데이터보여질때 멤버에대한 이미지가 필요하여 필드 추가 및 서비스수정
- 수정
=> ♻️ refactor(HAT-311): 게시물작성수정

community-app-external-api/src/main/java/io/howstheairtoday/appcommunityexternalapi/config/CorsConfig.java, community-app-external-api/src/main/java/io/howstheairtoday/appcommunityexternalapi/controller/PostController.java, community-app-external-api/src/main/java/io/howstheairtoday/appcommunityexternalapi/service/ExternalPostService.java
- 게시글 삭제수정 
- 기존에 바디로 받는값을  `@PathVariable`로 바꿈 
- 수정
=> ♻️ refactor(HAT-315): 게시글삭제수정

air-quality-app-batch/src/main/java/io/howstheairtoday/AirQualityAppBatchApplication.java, air-quality-app-batch/src/main/java/io/howstheairtoday/airqualityappbatch/config/BatchConfiguration.java, air-quality-app-batch/src/main/java/io/howstheairtoday/airqualityappbatch/config/PMForecastBatchConfiguration.java, air-quality-app-batch/src/main/java/io/howstheairtoday/airqualityappbatch/listener/JobCompletionNotificationListener.java, air-quality-app-batch/src/main/java/io/howstheairtoday/airqualityappbatch/scheduler/PMForecastSchedulerConfiguration.java, air-quality-app-batch/src/main/java/io/howstheairtoday/airqualityappbatch/scheduler/SchedulerConfiguration.java, air-quality-app-batch/src/main/java/io/howstheairtoday/airqualityappbatch/service/AirQualityRealTimeService.java, air-quality-app-batch/src/main/java/io/howstheairtoday/airqualityappbatch/util/PMForecastDtoToEntityConverter.java, air-quality-app-batch/src/main/java/io/howstheairtoday/airqualityappbatch/util/PMForecastEntityToDtoConverter.java, air-quality-client/src/main/java/io/howstheairtoday/airqualityclient/config/LoggingInterceptor.java, air-quality-domain-rds/build.gradle, air-quality-domain-rds/src/main/java/io/howstheairtoday/airqualitydomainrds/entity/BaseEntity.java, air-quality-domain-rds/src/main/java/io/howstheairtoday/airqualitydomainrds/entity/PMForecast.java
- 미세먼지/초미세먼지 주간예보 데이터를 데이터베이스에 저장하기 위함
- `LOGGER` -> `logger`
- `DtoToEntity`, `EntityToDto` 메서드 추가
3-2-1. 생성 쿼리
3-2-2. 업데이트 쿼리
- 매일 `5, 11, 17, 23`시 `15`분마다 Batch Job 실행
```yaml
app:
pmForecast:
cron: '0 15 5,11,17,23 * * *'
```
```java
@Scheduled(cron = "${app.pmForecast.cron}")
public void pmForecastBatchJob() {
...
}
```
=> ✨ feat(HAT-47): 미세먼지 주간예보 batch

module-security/src/main/java/io/howstheairtoday/filter/TokenCheckFilter.java
- TokenCheckFilter path 삭제
- 개발에 용이하도록 설정해놓은 path 삭제.
- api/v1/post URL도 토큰을 체크하도록 설정
=> ♻️  refactor: post URL 경로도 체크할 수 있도록 예외 경로 삭제

air-quality-app-external-api/src/docs/asciidoc/index.adoc, air-quality-app-external-api/src/main/java/io/howstheairtoday/appairqualityexternalapi/controller/AirQualityController.java, air-quality-app-external-api/src/main/java/io/howstheairtoday/appairqualityexternalapi/service/dto/response/AirQualityRankingResponse.java, air-quality-app-external-api/src/test/java/io/howstheairtoday/airqualityappexternalapi/controller/AirQualityControllerTest.java
- 클라이언트에서 사용하기 용이하도록 API 응답 수정
```java
@RequiredArgsConstructor
@Getter
public class AirQualityRankingResponse {
private final List<CurrentDustResponseDTO> bestRankingList;
private final List<CurrentDustResponseDTO> worstRankingList;
}
```
- 기존
```java
@GetMapping("/ranking")
public Map<String, List<CurrentDustResponseDTO>> getRanking() {
List<CurrentDustResponseDTO> bestList = airQualityRealTimeService.findBest10();
List<CurrentDustResponseDTO> worstList = airQualityRealTimeService.findWorst10();
List<CurrentDustResponseDTO> combinedList = new ArrayList<>();
combinedList.addAll(bestList);
combinedList.addAll(worstList);
Map<String, List<CurrentDustResponseDTO>> data = new HashMap<>();
data.put("ranking", combinedList);
return data;
}
```
- 수정
```java
@GetMapping("/ranking")
public …
```
=> ♻️ refactor(HAT-360): 실시간 대기 정보 랭킹 API 수정

community-app-external-api/src/main/java/io/howstheairtoday/appcommunityexternalapi/controller/PostController.java, community-app-external-api/src/main/java/io/howstheairtoday/appcommunityexternalapi/exception/dto/ErrorMessage.java, community-app-external-api/src/main/java/io/howstheairtoday/appcommunityexternalapi/exception/posts/PostImageFileSIzeExcetpion.java, community-domain-rds/src/main/java/io/howstheairtoday/communitydomainrds/querydsl/PostQslImpl.java
- 기존 게시판이미지수정 
- 서브모듈 community-yaml 에 3MB  추가 
-  기존 patch,create컨트롤러 수정 
-  이미지사이즈 Exception class 추가
=> 🐛fix(HAT-374): be게시판이미지수정

community-app-external-api/src/test/java/io/howstheairtoday/appcommunityexternalapi/controller/PostControllerTest.java
- 게시글 컨트롤러 작성 
- 작성되어있는 게시글 컨트롤러 모두를  `perform` 테스트 
- 전체 테스트 완료
=> ✅ test(HAT-394): 게시글 컨트롤러 작성

community-app-external-api/src/test/java/io/howstheairtoday/appcommunityexternalapi/controller/CommentControllerTest.java, community-app-external-api/src/test/java/io/howstheairtoday/appcommunityexternalapi/controller/LikeControllerTest.java
- 댓글, 좋아요 컨트롤러 테스트 작성
- 댓글과 좋아요 컨트롤러 mockMvc 사용해서 테스트 완료
- 댓글
- 좋아요
=> ✅ test(HAT-395): 댓글, 좋아요 컨트롤러 테스트
